"""Semantic validation of a parsed Flow.

Parsing (flow.py) guarantees structure; this module guarantees *meaning*:
parameter ranges, required params per op, destructive-command policy, and
assertion sanity. Everything headed for a device passes through here —
including flows generated by the future natural-language frontend.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .command import DESTRUCTIVE_OPS, LOG_PAGES, Op
from .flow import Assertion, Flow, Step

MAX_TRANSFER_BLOCKS = 65536  # sanity cap for a single logical read/write


@dataclass
class ValidationIssue:
    severity: str  # "error" | "warning"
    where: str
    message: str

    def __str__(self) -> str:
        return f"[{self.severity}] {self.where}: {self.message}"


@dataclass
class ValidationReport:
    issues: list[ValidationIssue] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(i.severity == "error" for i in self.issues)

    def error(self, where: str, message: str) -> None:
        self.issues.append(ValidationIssue("error", where, message))

    def warning(self, where: str, message: str) -> None:
        self.issues.append(ValidationIssue("warning", where, message))


def _require(report: ValidationReport, where: str, params: dict, keys: list[str]) -> bool:
    missing = [k for k in keys if k not in params]
    if missing:
        report.error(where, f"missing required params: {', '.join(missing)}")
        return False
    return True


def _validate_step(report: ValidationReport, flow: Flow, idx: int, step: Step) -> None:
    where = f"step {idx} ({step.command.op.value})"
    op = step.command.op
    params = step.command.params

    if op in DESTRUCTIVE_OPS and not flow.allow_destructive:
        report.error(
            where,
            "destructive/raw command requires 'allow_destructive: true' at flow level",
        )

    if op in (Op.READ, Op.WRITE):
        if _require(report, where, params, ["lba", "blocks"]):
            if not isinstance(params["lba"], int) or params["lba"] < 0:
                report.error(where, "'lba' must be a non-negative integer")
            blocks = params["blocks"]
            if not isinstance(blocks, int) or blocks <= 0:
                report.error(where, "'blocks' must be a positive integer")
            elif blocks > MAX_TRANSFER_BLOCKS:
                report.error(where, f"'blocks' exceeds sanity cap {MAX_TRANSFER_BLOCKS}")
        if op is Op.WRITE and "pattern" not in params:
            report.warning(where, "write without 'pattern' will use zeros")

    elif op is Op.GET_LOG:
        if _require(report, where, params, ["log"]):
            if params["log"] not in LOG_PAGES:
                report.error(
                    where,
                    f"unknown log page '{params['log']}' (known: {', '.join(LOG_PAGES)})",
                )

    elif op is Op.IDENTIFY_NAMESPACE:
        nsid = params.get("nsid", 1)
        if not isinstance(nsid, int) or nsid < 1:
            report.error(where, "'nsid' must be a positive integer")

    elif op in (Op.RAW_NVME, Op.RAW_SCSI):
        key = "cdb" if op is Op.RAW_SCSI else "opcode"
        if key not in params:
            report.error(where, f"raw command requires '{key}'")
        report.warning(where, "raw commands bypass the abstraction layer; review carefully")

    for a_idx, a in enumerate(step.assertions):
        _validate_assertion(report, f"{where} assert[{a_idx}]", a)


def _validate_assertion(report: ValidationReport, where: str, a: Assertion) -> None:
    if a.op not in Assertion.VALID_OPS:
        report.error(where, f"unknown assertion op '{a.op}' (valid: {', '.join(sorted(Assertion.VALID_OPS))})")
    if a.op != "exists" and a.value is None:
        report.error(where, f"assertion op '{a.op}' requires a 'value'")
    if not a.path or not isinstance(a.path, str):
        report.error(where, "assertion 'path' must be a non-empty string")


def validate_flow(flow: Flow) -> ValidationReport:
    """Run all semantic checks on a parsed flow."""
    report = ValidationReport()
    for idx, step in enumerate(flow.steps):
        _validate_step(report, flow, idx, step)
    return report
